services:
  - type: web
    name: icdbms-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn irt_crm.wsgi:application
    envVars:
      - fromDotEnv: true
    plan: free
    region: oregon
