# Generated by Django 5.1.7 on 2025-06-22 19:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('requested_by', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('filter_parameters', models.JSONField(blank=True, null=True)),
                ('requested_by_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Download Request',
                'verbose_name_plural': 'Download Requests',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_owner_name', models.CharField(max_length=100, unique=True)),
                ('account_owner_alias', models.CharField(max_length=50)),
                ('regions', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'User Region',
                'verbose_name_plural': 'User Regions',
                'db_table': 'user_regions',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.CharField(blank=True, db_column='Account_Id', max_length=18, null=True)),
                ('account_name', models.TextField(blank=True, db_column='Account_Name', null=True)),
                ('account_phone', models.TextField(blank=True, db_column='AccountPhone', null=True)),
                ('first_name', models.CharField(blank=True, db_column='FirstName', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, db_column='LastName', max_length=50, null=True)),
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
                ('organization_level', models.CharField(blank=True, db_column='OrganizationLevel', max_length=100, null=True)),
                ('department', models.CharField(blank=True, db_column='Department', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=200, null=True)),
                ('mobile', models.TextField(blank=True, db_column='MobilePhone', null=True)),
                ('phone', models.TextField(blank=True, db_column='Phone', null=True)),
                ('other_phone', models.TextField(blank=True, db_column='OtherPhone', null=True)),
                ('industry', models.CharField(blank=True, db_column='Industry', max_length=100, null=True)),
                ('mailing_country', models.TextField(blank=True, db_column='MailingCountry', null=True)),
                ('mailing_zip', models.TextField(blank=True, db_column='MailingPostalCode', null=True)),
                ('mailing_state', models.TextField(blank=True, db_column='MailingState', null=True)),
                ('mailing_city', models.TextField(blank=True, db_column='MailingCity', null=True)),
                ('website', models.CharField(blank=True, db_column='Website', max_length=200, null=True)),
                ('region', models.CharField(db_column='REGION', max_length=20)),
                ('contact_id', models.CharField(blank=True, db_column='Contact_Id', max_length=50, null=True)),
                ('zone', models.CharField(blank=True, db_column='Zone', max_length=50, null=True)),
                ('account_owner', models.CharField(blank=True, db_column='Account Owner', max_length=100, null=True)),
                ('created_by_id', models.CharField(blank=True, db_column='CreatedById', max_length=18, null=True)),
                ('created_date', models.DateField(blank=True, db_column='CreatedDate', null=True)),
                ('remarks', models.TextField(blank=True, db_column='Remarks', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='timestamp')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'accounts',
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='accounts_FirstNa_9a735a_idx'), models.Index(fields=['email'], name='accounts_Email_c503b4_idx'), models.Index(fields=['account_id'], name='accounts_Account_c72086_idx'), models.Index(fields=['phone', 'mobile'], name='accounts_Phone_ba1823_idx'), models.Index(fields=['region'], name='accounts_REGION_e59aee_idx'), models.Index(fields=['account_name'], name='accounts_Account_5b9319_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, db_column='Account_Id', max_length=18, null=True)),
                ('account_name', models.CharField(db_column='Account_Name', max_length=200)),
                ('billing_city', models.CharField(blank=True, db_column='BillingCity', max_length=100, null=True)),
                ('billing_country', models.CharField(blank=True, db_column='BillingCountry', max_length=100, null=True)),
                ('billing_postal_code', models.CharField(blank=True, db_column='BillingPostalCode', max_length=20, null=True)),
                ('billing_state', models.CharField(blank=True, db_column='BillingState', max_length=100, null=True)),
                ('billing_street', models.TextField(blank=True, db_column='BillingStreet', null=True)),
                ('created_by_id', models.CharField(blank=True, db_column='CreatedById', max_length=18, null=True)),
                ('created_date', models.DateField(blank=True, db_column='CreatedDate', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('industry', models.CharField(db_column='Industry', max_length=100)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('region', models.CharField(blank=True, db_column='REGION', max_length=100, null=True)),
                ('website', models.CharField(blank=True, db_column='Website', max_length=200, null=True)),
                ('zone', models.CharField(blank=True, db_column='Zone', max_length=50, null=True)),
                ('account_owner', models.CharField(blank=True, db_column='Account Owner', max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='timestamp')),
                ('linked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Account Record',
                'verbose_name_plural': 'Account Records',
                'db_table': 'account_records',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['account_id'], name='account_rec_Account_fe581f_idx'), models.Index(fields=['account_name'], name='account_rec_Account_9173e0_idx'), models.Index(fields=['industry'], name='account_rec_Industr_34e8f2_idx'), models.Index(fields=['billing_country'], name='account_rec_Billing_e1d9f7_idx'), models.Index(fields=['created_date'], name='account_rec_Created_58e559_idx')],
            },
        ),
    ]
