# Generated by Django 5.1.7 on 2025-06-14 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('salutation', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('mailing_street', models.TextField(blank=True, null=True)),
                ('account_id', models.CharField(blank=True, max_length=18, null=True)),
                ('mailing_city', models.TextField(blank=True, null=True)),
                ('mailing_state', models.TextField(blank=True, null=True)),
                ('mailing_zip', models.TextField(blank=True, null=True)),
                ('mailing_country', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('account_phone', models.TextField(blank=True, null=True)),
                ('mobile', models.TextField(blank=True, null=True)),
                ('fax', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('account_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('account_owner_alias', models.CharField(blank=True, max_length=50, null=True)),
                ('salesperson_sf_id', models.CharField(blank=True, max_length=18, null=True)),
                ('account_created_date', models.DateField(blank=True, null=True)),
                ('account_name', models.TextField(blank=True, null=True)),
                ('region', models.CharField(max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('requested_by', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
