# Generated by Django 5.1.7 on 2025-06-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountrecord_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='data_type',
            field=models.CharField(blank=True, default='contacts', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='page_context',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
