# Generated by Django 5.1.7 on 2025-06-16 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250614_2308'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['first_name', 'last_name'], name='accounts_first_n_92868b_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email'], name='accounts_email_04e851_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_id'], name='accounts_account_b1fcfd_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['phone', 'mobile'], name='accounts_phone_404aec_idx'),
        ),
    ]
