# Generated by Django 5.1.7 on 2025-06-17 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250614_2308'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('India', 'India'), ('Singapore', 'Singapore'), ('International', 'International')], default='India', max_length=50)),
            ],
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['first_name', 'last_name'], name='accounts_first_n_92868b_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['email'], name='accounts_email_04e851_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_id'], name='accounts_account_b1fcfd_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['phone', 'mobile'], name='accounts_phone_404aec_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
