# Generated by Django 5.1.7 on 2025-06-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_account_accounts_first_n_92868b_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['region'], name='accounts_region_1f8a1b_idx'),
        ),
    ]
