# Generated by Django 5.1.7 on 2025-06-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_accounts_region_1f8a1b_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_owner_name', models.CharField(max_length=100, unique=True)),
                ('account_owner_alias', models.CharField(max_length=50)),
                ('regions', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_regions',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
