# Generated by Django 5.2.4 on 2025-07-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountrecord_last_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='mailing_city',
        ),
        migrations.RemoveField(
            model_name='account',
            name='mailing_country',
        ),
        migrations.RemoveField(
            model_name='account',
            name='mailing_state',
        ),
        migrations.RemoveField(
            model_name='account',
            name='mailing_zip',
        ),
        migrations.RemoveField(
            model_name='account',
            name='website',
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, db_column='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, db_column='Country', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='state',
            field=models.CharField(blank=True, db_column='State', max_length=100, null=True),
        ),
    ]
