# Generated by Django 5.2.4 on 2025-07-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_accountrecord_account_rec_billing_e1d9f7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrecord',
            name='full_name',
            field=models.CharField(blank=True, db_column='FullName', max_length=200, null=True, verbose_name='Full Name'),
        ),
    ]
