# Generated by Django 5.2.4 on 2025-07-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accountrecord_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrecord',
            name='full_name',
        ),
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(blank=True, db_column='FullName', max_length=200, null=True, verbose_name='Full Name'),
        ),
    ]
