# Generated by Django 5.2.4 on 2025-07-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_accountrecord_full_name_account_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregion',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
