# Generated by Django 5.2.4 on 2025-07-05 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_account_created_by_id_account_created_by_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrecord',
            name='created_by_id',
        ),
        migrations.AddField(
            model_name='accountrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='CreatedById', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_record_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
