# Generated by Django 5.2.4 on 2025-07-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_accountrecord_created_by_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrecord',
            name='account_name',
            field=models.CharField(db_column='Account_Name', max_length=400, unique=True, verbose_name='Account Name'),
        ),
    ]
