# Generated by Django 5.2.4 on 2025-07-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_accountrecord_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrecord',
            name='account_name',
            field=models.CharField(db_column='Account_Name', max_length=400, verbose_name='Account Name'),
        ),
    ]
