# Generated by Django 5.2.4 on 2025-07-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_accountrecord_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contacts_city',
            field=models.CharField(blank=True, db_column='Contacts_City', max_length=100, null=True, verbose_name='Contacts City'),
        ),
        migrations.AddField(
            model_name='account',
            name='contacts_country',
            field=models.CharField(blank=True, db_column='Contacts_Country', max_length=100, null=True, verbose_name='Contacts Country'),
        ),
        migrations.AddField(
            model_name='account',
            name='contacts_state',
            field=models.CharField(blank=True, db_column='Contacts_State', max_length=100, null=True, verbose_name='Contacts State'),
        ),
    ]
