# Generated by Django 5.2.4 on 2025-07-10 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_account_contacts_city_account_contacts_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accountrecord',
            index=models.Index(fields=['account_name', 'created_date'], name='account_rec_Account_80dc25_idx'),
        ),
        migrations.AddIndex(
            model_name='accountrecord',
            index=models.Index(fields=['region'], name='account_rec_REGION_8d871b_idx'),
        ),
        migrations.AddIndex(
            model_name='accountrecord',
            index=models.Index(fields=['account_owner'], name='account_rec_Account_73033e_idx'),
        ),
        migrations.AddIndex(
            model_name='accountrecord',
            index=models.Index(fields=['city'], name='account_rec_City_34ce7b_idx'),
        ),
        migrations.AddIndex(
            model_name='accountrecord',
            index=models.Index(fields=['state'], name='account_rec_State_93e10a_idx'),
        ),
        migrations.AddIndex(
            model_name='accountrecord',
            index=models.Index(fields=['last_modified'], name='account_rec_last_mo_e6caba_idx'),
        ),
    ]
