# Generated by Django 5.2.3 on 2025-07-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_accountrecord_account_rec_account_80dc25_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(blank=True, db_column='Account_Id', max_length=58, null=True),
        ),
    ]
