# Generated by Django 5.2.3 on 2025-07-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_account_account_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountrecord',
            new_name='account_rec_country_1b2a93_idx',
            old_name='account_rec_Country_b0ed37_idx',
        ),
        migrations.RenameIndex(
            model_name='accountrecord',
            new_name='account_rec_city_db39d8_idx',
            old_name='account_rec_City_34ce7b_idx',
        ),
        migrations.RenameIndex(
            model_name='accountrecord',
            new_name='account_rec_state_da22e3_idx',
            old_name='account_rec_State_93e10a_idx',
        ),
        migrations.AlterField(
            model_name='accountrecord',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='accountrecord',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='accountrecord',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
    ]
